services:
    db:
        image: mysql:latest
        container_name: blablavelo_mysql
        restart: always
        environment:
            MYSQL_DATABASE: app
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: admin
            MYSQL_USER: admin
        healthcheck:
            test: ["CMD-SHELL", "mysql -u root -proot -e 'SELECT 1'"]
            interval: 10s
            retries: 5
            start_period: 120s
            timeout: 10s
        volumes:
            - mysql_blablavelo_data:/var/lib/mysql:rw
        networks:
            - blablavelo
        ports:
            - "9000:3306"
    # phpmyadmin:
    #     image: phpmyadmin:latest
    #     container_name: blablavelo_phpmyadmin
    #     restart: always
    #     depends_on:
    #         - db
    #     # ports:
    #     #     - "8081:80"
    #     environment:
    #         PMA_HOST: db
    #         MYSQL_ROOT_PASSWORD: root
    #     networks:
    #         - blablavelo
    php:
        image: blablavelo
        container_name: blablavelo_php8.3
        restart: always
        labels:
            - traefik.enable=true
            - traefik.http.routers.blablavelo-php.rule=Host(`blablavelo.ju2breizh.fr`)
        networks:
            - webgateway
            - blablavelo
        depends_on:
            db:
                condition: service_healthy
                restart: true
        build:
            context: .
            dockerfile: Dockerfile
volumes:
    mysql_blablavelo_data:
        driver: local

networks:
    blablavelo:
        driver: bridge
    webgateway:
        external: true
