services:
    db:
        image: mysql:latest
        container_name: blablavelo_mysql
        restart: always
        environment:
            MYSQL_DATABASE: app
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: admin
            MYSQL_USER: admin
        healthcheck:
            test: ["CMD-SHELL", "mysql -u root -proot -e 'SELECT 1'"]
            interval: 10s
            retries: 5
            start_period: 120s
            timeout: 10s
        volumes:
            - mysql_blablavelo_data:/var/lib/mysql:rw
        networks:
            - blablavelo
    # mailhog: # for dev only
    #     image: mailhog/mailhog
    #     container_name: hr-mailhog
    #     ports:
    #         - "1025:1025"
    #         - "8025:8025"
    #     environment:
    #         MH_STORAGE: memory
    #     networks:
    #         - blablavelo
    rabbit-mq:
        image: rabbitmq:latest
        container_name: rabbit-mq
        ports:
            - 5672:5672
        networks:
            - blablavelo
    php:
        image: blablavelo
        container_name: blablavelo_php8.3
        restart: always
        labels:
            - traefik.enable=true
            - traefik.http.routers.blablavelo-php.rule=Host(`blablavelo.ju2breizh.fr`)
        ports:
            - "9020:80"
        networks:
            - webgateway
            - blablavelo
        depends_on:
            db:
                condition: service_healthy
                restart: true
        build:
            context: .
            dockerfile: Dockerfile
        # volumes: # for dev env only
        #     - ./:/var/www/html
volumes:
    mysql_blablavelo_data:
        driver: local

networks:
    blablavelo:
        driver: bridge
    webgateway:
        external: true
