name: Deploy to Hostinger

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0' # ou la version de PHP que vous utilisez
        extensions: mbstring, intl, pdo, mysql, etc

    - name: Install dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

    - name: Run tests
      run: php bin/phpunit

    - name: Deploy to Hostinger
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        apt-get install -y lftp
        lftp -f "
        open $FTP_SERVER
        user $FTP_USERNAME $FTP_PASSWORD
        mirror --reverse --delete --verbose ./public /public_html
        bye
        "
